# Sales & Customer Data Analysis using SQL

In [1]:
import pandas as pd
import sqlite3

In [8]:
df=pd.read_csv("C:\\Users\\ACER\Downloads\Superstore.csv",encoding="latin1")

In [10]:
conn=sqlite3.connect("sales_data.db")

In [11]:
df.to_sql("sales_data",conn,if_exists="replace",index = False)

9994

In [12]:
query="""
select * from sales_data limit 5 ;
"""
pd.read_sql(query,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [21]:
query="""
select "Customer Name", Sales, Profit from sales_data limit 5;"""

pd.read_sql(query,conn)

     Customer Name     Sales    Profit
0      Claire Gute  261.9600   41.9136
1      Claire Gute  731.9400  219.5820
2  Darrin Van Huff   14.6200    6.8714
3   Sean O'Donnell  957.5775 -383.0310
4   Sean O'Donnell   22.3680    2.5164

In [20]:
query="""
select * from sales_data where profit >1000
"""
pd.read_sql(query,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,319,CA-2014-164973,11/4/2014,11/9/2014,Standard Class,NM-18445,Nathan Mautz,Home Office,United States,New York City,...,10024,East,TEC-MA-10002927,Technology,Machines,Canon imageCLASS MF7460 Monochrome Digital Las...,3991.980,2,0.0,1995.9900
1,354,CA-2016-129714,9/1/2016,9/3/2016,First Class,AB-10060,Adam Bellavance,Home Office,United States,New York City,...,10009,East,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,4355.168,4,0.2,1415.4296
2,510,CA-2015-145352,3/16/2015,3/22/2015,Standard Class,CM-12385,Christopher Martinez,Consumer,United States,Atlanta,...,30318,South,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,6354.950,5,0.0,3177.4750
3,516,CA-2017-127432,1/22/2017,1/27/2017,Standard Class,AD-10180,Alan Dominguez,Home Office,United States,Great Falls,...,59405,West,TEC-CO-10003236,Technology,Copiers,Canon Image Class D660 Copier,2999.950,5,0.0,1379.9770
4,995,CA-2014-117639,5/21/2014,5/25/2014,Standard Class,MW-18235,Mitch Willingham,Corporate,United States,Virginia Beach,...,23464,South,OFF-BI-10003925,Office Supplies,Binders,Fellowes PB300 Plastic Comb Binding Machine,2715.930,7,0.0,1276.4871
5,1086,US-2016-143819,3/1/2016,3/5/2016,Standard Class,KD-16270,Karen Daniels,Consumer,United States,Yonkers,...,10701,East,TEC-MA-10003979,Technology,Machines,Ativa V4110MDD Micro-Cut Shredder,4899.930,7,0.0,2400.9657
6,1455,CA-2016-133711,11/26/2016,11/29/2016,First Class,MC-17425,Mark Cousins,Corporate,United States,Mobile,...,36608,South,TEC-MA-10000010,Technology,Machines,Hewlett-Packard Deskjet 3050a All-in-One Color...,3040.000,8,0.0,1459.2000
7,1645,CA-2015-111829,3/19/2015,3/20/2015,First Class,FH-14365,Fred Hopkins,Corporate,United States,Seattle,...,98115,West,TEC-CO-10001766,Technology,Copiers,Canon PC940 Copier,3149.930,7,0.0,1480.4671
8,2183,CA-2016-128818,5/7/2016,5/11/2016,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,New York City,...,10009,East,TEC-MA-10000488,Technology,Machines,Bady BDG101FRU Card Printer,3999.950,5,0.0,1159.9855
9,2493,CA-2014-144624,11/19/2014,11/23/2014,Standard Class,JM-15865,John Murray,Consumer,United States,Jamestown,...,14701,East,TEC-PH-10002885,Technology,Phones,Apple iPhone 5,4548.810,7,0.0,1228.1787
10,2624,CA-2017-127180,10/22/2017,10/24/2017,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
11,2849,CA-2017-157854,4/8/2017,4/15/2017,Standard Class,DM-13345,Denise Monton,Corporate,United States,Roswell,...,30076,South,OFF-BI-10001359,Office Supplies,Binders,GBC DocuBind TL300 Electric Binding System,2690.970,3,0.0,1264.7559
12,3274,CA-2017-133865,5/8/2017,5/12/2017,Standard Class,PS-19045,Penelope Sewall,Home Office,United States,Los Angeles,...,90032,West,TEC-CO-10001046,Technology,Copiers,Canon Imageclass D680 Copier / Fax,3359.952,6,0.2,1049.9850
13,4094,CA-2015-102491,8/24/2015,8/28/2015,Standard Class,KW-16435,Katrina Willman,Consumer,United States,Florence,...,41042,South,TEC-MA-10000864,Technology,Machines,Cisco 9971 IP Video Phone Charcoal,3080.000,7,0.0,1416.8000
14,4099,CA-2014-116904,9/23/2014,9/28/2014,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,...,55407,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755
15,4191,CA-2017-166709,11/17/2017,11/22/2017,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
16,4278,US-2016-107440,4/16/2016,4/20/2016,Standard Class,BS-11365,Bill Shonely,Corporate,United States,Lakewood,...,8701,East,TEC-MA-10001047,Technology,Machines,"3D Systems Cube Printer, 2nd Generation, Magenta",9099.930,7,0.0,2365.9818
17,4620,CA-2017-145219,12/24/2017,12/25/2017,First Class,RM-19675,Robert Marley,Home Office,United States,Los Angeles,...,90049,West,TEC-CO-10001449,Technology,Copiers,Hewlett Packard LaserJet 3310 Copier,2879.952,6,0.2,1007.9832
18,5007,CA-2015-169796,11/9/2015,11/14/2015,Standard Class,Dp-13240,Dean percer,Home Office,United States,New York City,...,10035,East,TEC-MA-10000045,Technology,Machines,Zebra ZM400 Thermal Label Printer,2321.900,2,0.0,1114.5120
19,5127,CA-2014-160766,9/14/2014,9/14/2014,Same Day,DM-13015,Darrin Martin,Consumer,United States,New York City,...,10009,East,TEC-MA-10003979,Technology,Machines,Ativa V4110MDD Micro-Cut Shredder,2799.960,4,0.0,1371.9804
20,5563,CA-2017-133263,3/31/2017,4/2/2017,Second Class,JE-15610,Jim Epp,Corporate,United States,Atlanta,...,30318,South,TEC-CO-10001449,Technology,Copiers,Hewlett Packard LaserJet 3310 Copier,2999.950,5,0.0,1439.9760
21,5711,US-2015-160857,5/8/2015,5/15/2015,Standard Class,NW-18400,Natalie Webber,Consumer,United States,New York City,...,10024,East,TEC-CO-10004115,Technology,Copiers,Sharp AL-1530CS Digital Copier,2799.944,7,0.2,1014.9797
22,6341,CA-2017-143112,10/5/2017,10/9/2017,Standard Class,TS-21370,Todd Sumrall,Corporate,United States,New York City,...,10035,East,TEC-MA-10001047,Technology,Machines,"3D Systems Cube Printer, 2nd Generation, Magenta",5199.960,4,0.0,1351.9896
23,6426,CA-2016-143714,5/23/2016,5/27/2016,Standard Class,CC-12370,Christopher Conant,Consumer,United States,Philadelphia,...,19120,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,8399.976,4,0.4,1119.9968
24,6521,CA-2017-138289,1/16/2017,1/18/2017,Second Class,AR-10540,Andy Reiter,Consumer,United States,Jackson,...,49201,Central,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,5443.960,4,0.0,2504.2216
25,6627,CA-2014-145541,12/14/2014,12/21/2014,Standard Class,TB-21400,Tom Boeckenhauer,Consumer,United States,New York City,...,10024,East,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,6999.960,4,0.0,2239.9872
26,6818,CA-2014-144414,6/17/2014,6/21/2014,Standard Class,GH-14425,Gary Hwang,Consumer,United States,Seattle,...,98105,West,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,3266.376,3,0.2,1061.5722
27,6827,CA-2016-118689,10/2/2016,10/9/2016,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
28,7281,CA-2015-162782,2/21/2015,2/27/2015,Standard Class,PW-19240,Pierre Wener,Consumer,United States,Columbia,...,21044,East,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,2541.980,2,0.0,1270.9900
29,7667,US-2016-140158,10/4/2016,10/8/2016,Standard Class,DR-12940,Daniel Raglin,Home Office,United States,Providence,...,2908,East,TEC-CO-10001449,Technology,Copiers,Hewlett Packard LaserJet 3310 Copier,5399.910,9,0.0,2591.9568
30,7684,CA-2015-120782,4/28/2015,5/1/2015,First Class,SD-20485,Shirley Daniels,Home Office,United States,Midland,...,48640,Central,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,3812.970,3,0.0,1906.4850
31,7819,CA-2016-138478,10/21/2016,10/26/2016,Second Class,DP-13390,Dennis Pardue,Home Office,United States,North Las Vegas,...,89031,West,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,4535.976,3,0.2,1644.2913
32,7915,CA-2017-165323,6/17/2017,6/21/2017,Standard Class,SR-20740,Steven Roelle,Home Office,United States,New York City,...,10024,East,TEC-MA-10003673,Technology,Machines,Hewlett-Packard Desktjet 6988DT Refurbished Pr...,3404.500,5,0.0,1668.2050
33,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
34,8205,CA-2015-114811,11/8/2015,11/8/2015,Same Day,KD-16495,Keith Dawkins,Corporate,United States,New York City,...,10024,East,TEC-MA-10000045,Technology,Machines,Zebra ZM400 Thermal Label Printer,4643.800,4,0.0,2229.0240
35,8489,CA-2016-158841,2/2/2016,2/4/2016,Second Class,SE-20110,Sanjit Engle,Consumer,United States,Arlington,...,22204,South,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.950,5,0.0,2799.9840
36,8750,US-2015-163825,6/16/2015,6/19/2015,First Class,LC-16885,Lena Creighton,Consumer,United States,New York City,...,10009,East,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,3050.376,3,0.2,1143.8910
37,8859,CA-2017-135909,10/13/2017,10/20/2017,Standard Class,JW-15220,Jane Waco,Corporate,United States,Sacramento,...,95823,West,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.960,5,0.2,1906.4850
38,8991,US-2015-128587,12/24/2015,12/30/2015,Standard Class,HM-14860,Harry Marie,Corporate,United States,Springfield,...,65807,Central,TEC-CO-10003763,Technology,Copiers,Canon PC1060 Personal Laser Copier,4899.930,7,0.0,2302.9671
39,9040,CA-2016-117121,12/17/2016,12/21/2016,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,...,48205,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,0.0,4946.3700
40,9271,US-2017-102183,8/21/2017,8/28/2017,Standard Class,PK-19075,Pete Kriz,Consumer,United States,New York City,...,10035,East,OFF-BI-10001359,Office Supplies,Binders,GBC DocuBind TL300 Electric Binding System,4305.552,6,0.2,1453.1238
41,9742,CA-2015-117086,11/8/2015,11/12/2015,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,...,5408,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.900,5,0.0,1013.1270

In [22]:
query="""
select * from sales_data where Category='Furniture' and sales >500; 
"""
pd.read_sql(query,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
1,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
2,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
3,25,CA-2015-106320,9/25/2015,9/30/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,...,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.6300,3,0.00,240.2649
4,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,9880,CA-2016-122581,8/21/2016,8/25/2016,Standard Class,JK-15370,Jay Kimmel,Consumer,United States,New York City,...,10035,East,FUR-CH-10002961,Furniture,Chairs,"Leather Task Chair, Black",573.1740,7,0.10,63.6860
463,9908,US-2015-129007,9/13/2015,9/15/2015,First Class,KD-16615,Ken Dana,Corporate,United States,Anaheim,...,92804,West,FUR-CH-10000155,Furniture,Chairs,Global Comet Stacking Armless Chair,717.7200,3,0.20,71.7720
464,9920,CA-2016-149272,3/15/2016,3/19/2016,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Bryan,...,77803,Central,FUR-CH-10000863,Furniture,Chairs,Novimex Swivel Fabric Task Chair,528.4300,5,0.30,-143.4310
465,9932,CA-2015-104948,11/13/2015,11/17/2015,Standard Class,KH-16510,Keith Herrera,Consumer,United States,San Bernardino,...,92404,West,FUR-BO-10004357,Furniture,Bookcases,O'Sullivan Living Dimensions 3-Shelf Bookcases,683.3320,4,0.15,-40.1960
466,9948,CA-2017-121559,6/1/2017,6/3/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,FUR-CH-10003746,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.8800,6,0.00,539.2464

In [27]:
# Total Sales by Category

query="""
select category,Sum(Sales)as Total_Sales from sales_data group by Category;
"""

pd.read_sql(query,conn)

          Category  Total_Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [28]:
#Total Sales by Category (Highest First)
query="""
select category,Sum(Sales)as Total_Sales from sales_data group by Category Order by Total_Sales Desc;
"""
pd.read_sql(query,conn)

          Category  Total_Sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

In [30]:
#Count Total Orders
query ="""
select count(*) as Total_Orders from sales_data;
"""

pd.read_sql(query,conn)

   Total_Orders
0          9994

In [36]:
# Count by Category
query="""
select Category, count(*) as Total_Orders from sales_data Group by Category;
"""
pd.read_sql(query,conn)

          Category  Total_Orders
0        Furniture          2121
1  Office Supplies          6026
2       Technology          1847

In [39]:
#Average Sales by Category
query="""
select Category,AVG(Sales) as Average_Sales from sales_data group by Category;
"""
pd.read_sql(query,conn)

          Category  Average_Sales
0        Furniture     349.834887
1  Office Supplies     119.324101
2       Technology     452.709276

In [41]:
#Highest Sales Value
query="""
select max(Sales) as Highest_Sales from sales_data;
"""
pd.read_sql(query,conn)

   Highest_Sales
0       22638.48

In [42]:
#Lowest Profit Value
query="""
select min(Profit) as Lowest_Profit from sales_data;
"""
pd.read_sql(query,conn)

   Lowest_Profit
0      -6599.978

In [45]:
#Highest Profit by Category
query="""
select Category, max(Profit)as Highest_Profit from sales_data group by Category;
"""
pd.read_sql(query,conn)

          Category  Highest_Profit
0        Furniture        1013.127
1  Office Supplies        4946.370
2       Technology        8399.976

In [46]:
#Total Sales > 500000
query="""
select Category,sum(Sales) as Total_Sales from sales_data group by category having Sum(Sales)>500000;
"""
pd.read_sql(query,conn)

          Category  Total_Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [47]:
#Average Profit > 50
query="""
select Category,Avg(Profit)as Avg_Profit from sales_data group by category having Avg(Profit)>50;
"""
pd.read_sql(query,conn)

     Category  Avg_Profit
0  Technology   78.752002

In [50]:
#Create sales segments(High Sales,Medium Sales,Low Sales):

query="""
Select Sales,

Case
  When Sales>1000 Then 'High Sales'
  When Sales>500 Then 'Medium Sales'
  Else 'Low Sales'
END as Sales_Category

from Sales_data
limit 10;
"""
pd.read_sql(query,conn)

      Sales Sales_Category
0  261.9600      Low Sales
1  731.9400   Medium Sales
2   14.6200      Low Sales
3  957.5775   Medium Sales
4   22.3680      Low Sales
5   48.8600      Low Sales
6    7.2800      Low Sales
7  907.1520   Medium Sales
8   18.5040      Low Sales
9  114.9000      Low Sales

In [51]:
#Profit Status
query="""
select Profit,

Case
  when Profit>0 Then 'Profit'
  else 'Loss'
End As Profit_Status

from sales_data
limit 10;
"""
pd.read_sql(query,conn)

     Profit Profit_Status
0   41.9136        Profit
1  219.5820        Profit
2    6.8714        Profit
3 -383.0310          Loss
4    2.5164        Profit
5   14.1694        Profit
6    1.9656        Profit
7   90.7152        Profit
8    5.7825        Profit
9   34.4700        Profit

## Real Business SQL Analysis

In [52]:
#Top 10 Customers by Sales

query="""
Select "Customer Name",
       Sum(Sales)As Total_Sales
From sales_data
Group By "Customer Name"
Order By Total_Sales Desc
limit 10;
"""
pd.read_sql(query,conn)

        Customer Name  Total_Sales
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072

Purpose
- To identify top revenue-generating customers.
- To understand customer contribution to total sales.
- To support customer retention strategies.

In [53]:
#Most Profitable Categories
query="""
select Category,sum(Profit)As Total_Profit
from sales_data
group by Category
order by Total_Profit Desc;
"""
pd.read_sql(query,conn)

          Category  Total_Profit
0       Technology   145454.9481
1  Office Supplies   122490.8008
2        Furniture    18451.2728

Purpose
- To identify categories generating maximum profit.
- To understand overall category performance.
- To support strategic business decisions.

In [54]:
#Loss-Making Sub-Categories
query="""
select "Sub-Category",
      Sum(Profit)as Total_Profit
from sales_data
Group by "Sub-Category"
Having Sum(Profit)<0
Order By Total_Profit;
"""
pd.read_sql(query,conn)

  Sub-Category  Total_Profit
0       Tables   -17725.4811
1    Bookcases    -3472.5560
2     Supplies    -1189.0995

Purpose
- To identify products causing business losses.
- To detect weak-performing product segments.
- To support inventory and pricing decisions.

In [65]:
#Monthly Sales Trend
df["Order Date"]=pd.to_datetime(df["Order Date"])
df["Order Month"]=df["Order Date"].dt.month

df.to_sql("sales_data",conn,if_exists="replace",index=False)

9994

In [66]:


query="""
select
  strftime('%m',"Order Date")As Order_Month,
  Sum(Sales)as Total_Sales
from sales_data
group by Order_Month
order by Order_Month;
"""
pd.read_sql(query,conn)

   Order_Month  Total_Sales
0           01   94924.8356
1           02   59751.2514
2           03  205005.4888
3           04  137762.1286
4           05  155028.8117
5           06  152718.6793
6           07  147238.0970
7           08  159044.0630
8           09  307649.9457
9           10  200322.9847
10          11  352461.0710
11          12  325293.5035

Purpose
- To analyze monthly sales performance.
- To identify seasonal sales trends.
- To support forecasting and business planning.

In [67]:
#Discount Impact on Profit
query="""
select Discount, Avg(Profit)as Average_Profit
from sales_data
group by Discount
order by Discount;
"""
pd.read_sql(query,conn)

    Discount  Average_Profit
0       0.00       66.900292
1       0.10       96.055074
2       0.15       27.288298
3       0.20       24.702572
4       0.30      -45.679636
5       0.32      -88.560656
6       0.40     -111.927429
7       0.45     -226.646464
8       0.50     -310.703456
9       0.60      -43.077212
10      0.70      -95.874060
11      0.80     -101.796797

Purpose
- To analyze relationship between discount and profitability.
- To understand whether high discounts hurt business profit.
- To support pricing strategy decisions.

In [73]:
#Shipping Performance Analysis
df["Ship Date"]=pd.to_datetime(df["Ship Date"])
df["Shipping_Days"]=(df["Ship Date"]-df["Order Date"]).dt.days
df.to_sql("sales_data",conn,if_exists="replace",index=False)

9994

In [74]:
query="""
select Region,
   Avg(Shipping_Days) as Avg_Shipping_Days
from sales_data
group by Region
order by Avg_Shipping_Days Desc;
"""
pd.read_sql(query,conn)

    Region  Avg_Shipping_Days
0  Central           4.058115
1    South           3.958025
2     West           3.929753
3     East           3.908708

Purpose
- To compare delivery performance across regions.
- To identify regions with slower shipping efficiency.
- To support logistics optimization.

In [78]:
#Customer Segmentation
query="""
select "Customer Name",
      Sum(Sales)as Total_Sales,
CASE
  When Sum(Sales)>10000 Then 'High Value'
  When Sum(Sales)>5000 Then 'Medium Value'
  Else 'Low Value'
End as Customer_Segment
from sales_data
group by "Customer Name"
order by "Total Sales" Desc;
"""
pd.read_sql(query,conn)

          Customer Name  Total_Sales Customer_Segment
0    Zuschuss Donatelli     1493.944        Low Value
1      Zuschuss Carroll     8025.707     Medium Value
2        Yoseph Carroll     5454.350     Medium Value
3         Yana Sorensen     6720.444     Medium Value
4          Xylona Preis     2374.658        Low Value
..                  ...          ...              ...
788           Adam Hart     3250.337        Low Value
789     Adam Bellavance     7755.620     Medium Value
790      Aaron Smayling     3050.692        Low Value
791       Aaron Hawkins     1744.700        Low Value
792       Aaron Bergman      886.156        Low Value

[793 rows x 3 columns]

Purpose
- To segment customers based on spending behavior.
- To identify high-value customers.
- To support targeted marketing and retention strategies.